name: Telegram Sync

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Needed to push changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Telegram sync
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          DEST_CHANNEL: ${{ secrets.DEST_CHANNEL }}
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
          BLACKLIST: ${{ secrets.BLACKLIST }}
          WHITELIST: ${{ secrets.WHITELIST }}
        run: |
          if [ ! -f sent_hashes.txt ]; then touch sent_hashes.txt; fi
          python main.py

      - name: Commit and push sent_hashes.txt
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add sent_hashes.txt
          git commit -m "chore: update sent_hashes [skip ci]" || echo "No changes to commit"
          git push

